pyinstaller main.py ^
--paths ../../ ^
--collect-all "pypdfium2_raw" ^
--collect-all "pypdfium2" ^
--add-data "../../models/mixed.onnx:./models" ^
--add-data "../../models/board_segmenter.onnx:./models" ^
--add-data "../../config.ini:." ^
--add-data "../../img:./img" ^
--add-data "../../sounds:./sounds" ^
--icon "../../img/Icons/shogi_eye.ico" ^
--windowed ^
--name "ShogiVision" ^
--onefile